//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BikeStoreEntities : DbContext
    {
        public BikeStoreEntities()
            : base("name=BikeStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dang_Nhap> Dang_Nhap { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hang { get; set; }
        public virtual DbSet<Cua_Hang> Cua_Hang { get; set; }
        public virtual DbSet<Don_Hang> Don_Hang { get; set; }
        public virtual DbSet<Khach_Hang> Khach_Hang { get; set; }
        public virtual DbSet<Nhan_Vien> Nhan_Vien { get; set; }
        public virtual DbSet<Loai_SP> Loai_SP { get; set; }
        public virtual DbSet<Nhan_Hieu> Nhan_Hieu { get; set; }
        public virtual DbSet<Nhap_Lieu> Nhap_Lieu { get; set; }
        public virtual DbSet<San_Pham> San_Pham { get; set; }
        public virtual DbSet<Ton_Kho> Ton_Kho { get; set; }
        public virtual DbSet<view_DonHangKhachDaMua> view_DonHangKhachDaMua { get; set; }
        public virtual DbSet<view_ThongTinGiaoHang> view_ThongTinGiaoHang { get; set; }
        public virtual DbSet<view_TongTienMotDon> view_TongTienMotDon { get; set; }
    
        public virtual ObjectResult<Nhan_Vien> sp_FindAllEmployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nhan_Vien>("sp_FindAllEmployee");
        }
    
        public virtual ObjectResult<Nhan_Vien> sp_FindAllEmployee(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nhan_Vien>("sp_FindAllEmployee", mergeOption);
        }
    
        public virtual ObjectResult<Nhan_Vien> sp_FindEmployeeByName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nhan_Vien>("sp_FindEmployeeByName", nameParameter);
        }
    
        public virtual ObjectResult<Nhan_Vien> sp_FindEmployeeByName(string name, MergeOption mergeOption)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nhan_Vien>("sp_FindEmployeeByName", mergeOption, nameParameter);
        }
    
        public virtual ObjectResult<view_ThongTinGiaoHang> sp_FindBillEmployee(Nullable<int> idEmployee)
        {
            var idEmployeeParameter = idEmployee.HasValue ?
                new ObjectParameter("IdEmployee", idEmployee) :
                new ObjectParameter("IdEmployee", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<view_ThongTinGiaoHang>("sp_FindBillEmployee", idEmployeeParameter);
        }
    
        public virtual ObjectResult<view_ThongTinGiaoHang> sp_FindBillEmployee(Nullable<int> idEmployee, MergeOption mergeOption)
        {
            var idEmployeeParameter = idEmployee.HasValue ?
                new ObjectParameter("IdEmployee", idEmployee) :
                new ObjectParameter("IdEmployee", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<view_ThongTinGiaoHang>("sp_FindBillEmployee", mergeOption, idEmployeeParameter);
        }
    }
}
