//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cua_Hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cua_Hang()
        {
            this.Don_Hang = new HashSet<Don_Hang>();
            this.Nhan_Vien = new HashSet<Nhan_Vien>();
            this.Ton_Kho = new HashSet<Ton_Kho>();
        }
    
        public int Ma_Cua_Hang { get; set; }
        public string Ten_Cua_Hang { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string Duong { get; set; }
        public string Thanh_Pho { get; set; }
        public string Tinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don_Hang> Don_Hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nhan_Vien> Nhan_Vien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ton_Kho> Ton_Kho { get; set; }
    }
}
