//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dang_Nhap
    {
        public int Ma_Nhan_Vien { get; set; }
        public string Mat_Khau { get; set; }
        public Nullable<byte> Admin { get; set; }
    
        public virtual Nhan_Vien Nhan_Vien { get; set; }
    }
}
