//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Don_Hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Don_Hang()
        {
            this.Chi_Tiet_Don_Hang = new HashSet<Chi_Tiet_Don_Hang>();
        }
    
        public int Ma_Don_Hang { get; set; }
        public Nullable<int> Ma_KH { get; set; }
        public byte Trang_Thai_Giao_Hang { get; set; }
        public System.DateTime Ngay_Dat_Hang { get; set; }
        public System.DateTime Ngay_Yeu_Cau_Giao_Hang { get; set; }
        public Nullable<System.DateTime> Ngay_Van_Chuyen { get; set; }
        public int Ma_Cua_Hang { get; set; }
        public int Ma_Nhan_Vien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hang { get; set; }
        public virtual Cua_Hang Cua_Hang { get; set; }
        public virtual Khach_Hang Khach_Hang { get; set; }
        public virtual Nhan_Vien Nhan_Vien { get; set; }
    }
}
