//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhap_Lieu
    {
        public int Ma_Cua_Hang { get; set; }
        public int Ma_San_Pham { get; set; }
        public Nullable<int> So_Luong { get; set; }
        public Nullable<System.DateTime> Ngay_Nhap { get; set; }
    
        public virtual San_Pham San_Pham { get; set; }
    }
}
