//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class San_Pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public San_Pham()
        {
            this.Chi_Tiet_Don_Hang = new HashSet<Chi_Tiet_Don_Hang>();
            this.Nhap_Lieu = new HashSet<Nhap_Lieu>();
            this.Ton_Kho = new HashSet<Ton_Kho>();
        }
    
        public int Ma_San_Pham { get; set; }
        public string Ten_San_Pham { get; set; }
        public int Ma_Nhan_Hieu { get; set; }
        public int Ma_Loai_SP { get; set; }
        public short Nam_Ra_Doi { get; set; }
        public decimal Gia_SP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hang { get; set; }
        public virtual Loai_SP Loai_SP { get; set; }
        public virtual Nhan_Hieu Nhan_Hieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nhap_Lieu> Nhap_Lieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ton_Kho> Ton_Kho { get; set; }
    }
}
