//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_DonHangKhachDaMua
    {
        public Nullable<int> Ma_KH { get; set; }
        public string TenKH { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string Dia_Chi { get; set; }
        public int Ma_Don_Hang { get; set; }
        public int Ma_Nhan_Vien { get; set; }
    }
}
