//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQTCSDL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ThongTinGiaoHang
    {
        public Nullable<int> Ma_KH { get; set; }
        public string TenKH { get; set; }
        public int Ma_Don_Hang { get; set; }
        public byte Trang_Thai_Giao_Hang { get; set; }
        public System.DateTime Ngay_Dat_Hang { get; set; }
        public System.DateTime Ngay_Yeu_Cau_Giao_Hang { get; set; }
        public Nullable<System.DateTime> Ngay_Van_Chuyen { get; set; }
        public Nullable<decimal> TongTienCuaDon { get; set; }
        public string Ten_San_Pham { get; set; }
        public decimal Gia_SP { get; set; }
    }
}
